FROM registry.access.redhat.com/ubi9/nodejs-24:latest

WORKDIR /opt/app-root/src

COPY package*.json ./
RUN npm ci

COPY . .

USER 0

RUN npm run build \
  && chgrp -R 0 /opt/app-root/src \
  && chmod -R g=u /opt/app-root/src

USER 1001

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]
