apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: workshop
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: segredos-teste
    creationPolicy: Owner
  data:
    - secretKey: segredo-1
      remoteRef:
        key: segredosTeste
        property: segredo-1

    - secretKey: segredo-2
      remoteRef:
        key: segredosTeste
        property: segredo-2

    - secretKey: segredo-3
      remoteRef:
        key: segredosTeste
        property: segredo-3