apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: segredos-teste-ces
spec:
  externalSecretName: segredos-teste
  namespaceSelectors:
    - matchLabels:
        team: plataforma
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secretsmanager
      kind: ClusterSecretStore
    target:
      name: segredos-teste
      creationPolicy: Owner
    data:
      - secretKey: segredo-1
        remoteRef:
          key: segredosTeste
          property: segredo-1
      - secretKey: segredo-2
        remoteRef:
          key: segredosTeste
          property: segredo-2
      - secretKey: segredo-3
        remoteRef:
          key: segredosTeste
          property: segredo-3