FROM registry.redhat.io/rhbk/keycloak-rhel9:26.4 as builder

WORKDIR /opt/keycloak

ENV KC_HEALTH_ENABLED=true \
    KC_METRICS_ENABLED=true \
    KC_DB=postgres

# Adiciona o tema customizadao
COPY --chown=keycloak:keycloak ./themes /opt/keycloak/themes/

RUN /opt/keycloak/bin/kc.sh build


####################################################

FROM registry.redhat.io/rhbk/keycloak-rhel9:26.4
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]