quarkus.oidc.auth-server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080/realms/workshop}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID:ms-movies}

%dev.quarkus.tls.trust-all=true

quarkus.container-image.build=true
quarkus.openshift.route.expose=true

quarkus.openshift.env.vars.KEYCLOAK_SERVER_URL=https://rhbk.apps.bruno-cluster.sandbox2971.opentlc.com/realms/workshop
quarkus.openshift.env.vars.KEYCLOAK_CLIENT_ID=ms-movies

%prod.quarkus.openshift.mounts.route-ca.path=/deployments/route-ca
%prod.quarkus.openshift.config-map-volumes.route-ca.config-map-name=ingress-route-ca

%prod.quarkus.oidc.tls.tls-configuration-name=keycloak-tls
%prod.quarkus.tls.keycloak-tls.trust-store.pem.certs=/deployments/route-ca/route-ca.crt