quarkus.oidc.auth-server-url=${KEYCLOAK_SERVER_URL:http://localhost:8080/realms/workshop}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID:ms-movies}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET:txtBj1SRWByGdH435mjwukW9aVI1DBlH}

quarkus.kubernetes-client.connection-timeout=60S
quarkus.kubernetes-client.request-timeout=90S

%dev.quarkus.tls.trust-all=true

#quarkus.container-image.build=true
quarkus.openshift.route.expose=true

%prod.quarkus.openshift.mounts.route-ca.path=/deployments/route-ca
%prod.quarkus.openshift.config-map-volumes.route-ca.config-map-name=ingress-route-ca

%prod.quarkus.oidc.tls.tls-configuration-name=keycloak-tls
%prod.quarkus.tls.keycloak-tls.trust-store.pem.certs=/deployments/route-ca/route-ca.crt

### Opensfhit Environment Variables ###
quarkus.openshift.env.vars.KEYCLOAK_SERVER_URL=https://rhbk.apps.bruno-cluster.sandbox2971.opentlc.com/realms/workshop
quarkus.openshift.env.vars.KEYCLOAK_CLIENT_ID=ms-movies
quarkus.openshift.env.vars.KEYCLOAK_CLIENT_SECRET=kXUsxadJeaDBi1FACg2gVl8fRRP7UbGs
quarkus.openshift.env.secrets=segredos-teste